name: setup-node

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
