name: Lint Commit Messages

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      # HACK: https://github.com/conventional-changelog/commitlint/issues/3256#issuecomment-1460989769
      - run: rm -f tsconfig.json
      - uses: wagoid/commitlint-github-action@v5
